name: test-build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      
    # Install Julia    
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.0
      with:
        version: 1.3
        arch: x64
        show-versioninfo: true
    
    # Install Jupyter with Julia kernel
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        python-version: 3.x
    - name: Setup Jupyter
      run: conda install -c conda-forge notebook
    - name: Setup IJulia
      run: julia -e 'using Pkg; Pkg.add("IJulia")'
  


