name: test-build

on: [push]

jobs:
  build:
    timeout-minutes: 20

    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, ubuntu-18.04, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    # Install Julia
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.0
      with:
        version: 1.3
        arch: x64
        show-versioninfo: true

    # Install Jupyter with Julia kernel
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        miniconda-version: 'latest'
      run: |
        conda update conda
        conda create -n bmlip python=3.7 anaconda
        source activate bmlip

    - name: Setup Jupyter
      run: |
        conda list
        conda install -c anaconda jupyter
        conda install -c conda-forge notebook
        conda install -c conda-forge jupyterlab
        conda list

    - name: Setup IJulia
      run: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.status(); using IJulia; installkernel("julia")'

    # Clone repo
    - name: Clone BMLIP repo
      run: |
        git clone https://github.com/bertdv/BMLIP.git
        cd BMLIP/lessons/notebooks

    # Run lesson notebooks
    - name: Test notebook 00
      run: |
        jupyter nbconvert --to notebook --inplace --execute 00-Course-Outline-and-Admin-Issues.ipynb
