name: test-build

on: [push]

jobs:
  build:
    timeout-minutes: 60

    strategy:
      matrix:
        # platform: [windows-latest, ubuntu-latest, ubuntu-18.04, macos-latest]
        platform: [ubuntu-latest, ubuntu-18.04, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    # Clone repo
    - name: Checkout BMLIP repo
      uses: actions/checkout@v2
      with:
        ref: master

    # Setup Miniconda environment
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        miniconda-version: 'latest'
        python-version: 3.7

    # Install Python dependencies
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        conda install -c anaconda jupyter
        conda install -c conda-forge matplotlib
        conda install -c anaconda graphviz 
        conda list

    # Install Julia
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.0
      with:
        version: 1.3
        arch: x64
        show-versioninfo: true

    # Add IJulia kernel to Jupyter
    - name: Install IJulia kernel
      run: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.status(); using IJulia; installkernel("julia")'

    # Run lesson notebooks
    - name: Test notebook 00
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/00-Course-Outline-and-Admin-Issues.ipynb

    - name: Test notebook 01
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/01-Machine-Learning-Overview.ipynb

    - name: Test notebook 02
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/02-Probability-Theory-Review.ipynb

    - name: Test notebook 03
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/03-Bayesian-Machine-Learning.ipynb

    - name: Test notebook 04
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/04-The-Gaussian-Distribution.ipynb

    - name: Test notebook 05
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/05-The-Multinomial-Distribution.ipynb

    - name: Test notebook 06
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/06-Regression.ipynb

    - name: Test notebook 07
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/07-Generative-Classification.ipynb

    - name: Test notebook 08
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/08-Discriminative-Classification.ipynb

    - name: Test notebook 09
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/09-Latent-Variable-Models-and-VB.ipynb

    - name: Test notebook 10
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/10-Factor-Graphs.ipynb

    - name: Test notebook 11
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/11-Dynamic-Models.ipynb

    - name: Test notebook 12
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/12-Intelligent-Agents-and-Active-Inference.ipynb

    # - name: Test notebook PP-1-variational
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-1-variational.ipynb
    #
    # - name: Test notebook PP-1-sampling
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-1-sampling.ipynb
    #
    # - name: Test notebook PP-2-variational
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-2-variational.ipynb
    #
    # - name: Test notebook PP-2-sampling
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-2-sampling.ipynb
    #
    # - name: Test notebook PP-3-variational
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-3-variational.ipynb
    #
    # - name: Test notebook PP-3-sampling
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-3-sampling.ipynb
    #
    # - name: Test notebook PP-4-variational
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-4-variational.ipynb
    #
    # - name: Test notebook PP-4-sampling
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/probprog/Probabilistic-Programming-4-sampling.ipynb
