name: test-build

on: [push]

jobs:
  build:
    timeout-minutes: 300

    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    # Clone repo
    - name: Checkout BMLIP repo
      uses: actions/checkout@v2
      with:
        ref: master

    # Install GraphViz
    - name: Setup GraphViz
      uses: kamiazya/setup-graphviz@v1

    # Setup Miniconda environment
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        miniconda-version: 'latest'
        python-version: 3.7

    # Install Python dependencies
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        conda install -c anaconda jupyter
        conda install -c conda-forge matplotlib
        conda install -c anaconda graphviz

    # Install Julia 1.4
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: "1.4.2"
        arch: x64
        show-versioninfo: true
    - run: ln -s -f /Users/runner/hostedtoolcache/julia/1.4.2/x64/bin/julia /usr/local/bin/julia
      shell: bash -l {0}
      if: matrix.platform == 'macos-latest'

    # Add IJulia kernel to Jupyter
    - name: Install IJulia kernel
      shell: bash -l {0}
      run: julia -e 'using Pkg; Pkg.add("IJulia"); using IJulia; installkernel("julia")'

    # Run lesson notebooks
    - name: Test notebook 00
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/00-Course-Outline-and-Admin-Issues.ipynb

    - name: Test notebook 01
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/01-Machine-Learning-Overview.ipynb

    - name: Test notebook 02
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/02-Probability-Theory-Review.ipynb

    - name: Test notebook 03
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/03-Bayesian-Machine-Learning.ipynb

    - name: Test notebook 04
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/04-The-Gaussian-Distribution.ipynb

    - name: Test notebook 05
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/05-The-Multinomial-Distribution.ipynb

    - name: Test notebook 06
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/06-Regression.ipynb

    - name: Test notebook 07
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/07-Generative-Classification.ipynb

    - name: Test notebook 08
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/08-Discriminative-Classification.ipynb

    # - name: Test notebook 09
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/09-Latent-Variable-Models-and-VB.ipynb

    - name: Test notebook 10
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/10-Factor-Graphs.ipynb

    - name: Test notebook 11
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/11-Dynamic-Models.ipynb

    - name: Test notebook 12
      shell: bash -l {0}
      run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/notebooks/12-Intelligent-Agents-and-Active-Inference.ipynb

    # - name: Test notebook PP-1
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/exercises/probprog_solutions/Probabilistic-Programming-1_solutions.ipynb
    #
    # - name: Test notebook PP-2
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/exercises/probprog_solutions/Probabilistic-Programming-2_solutions.ipynb
    #
    # - name: Test notebook PP-3
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/exercises/probprog_solutions/Probabilistic-Programming-3_solutions.ipynb
    #
    # - name: Test notebook PP-4
    #   shell: bash -l {0}
    #   run: jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=-1 lessons/exercises/probprog_solutions/Probabilistic-Programming-4_solutions.ipynb
