name: test-build

on: [push]

jobs:
  build:
    timeout-minutes: 20

    strategy:
      matrix:
        # platform: [windows-latest, ubuntu-latest, ubuntu-18.04, macos-latest]
        platform: [ubuntu-latest, ubuntu-18.04, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    # Clone repo
    - name: Checkout BMLIP repo
      uses: actions/checkout@v2
        with:
          ref: master

    # Install Miniconda environment
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        miniconda-version: 'latest'
        activate-environment: bmlip-env
        environment-file: BMLIP/.github/workflows/environment.yml
        python-version: 3.7
    - shell: bash -l {0}
      run: |
        conda info
        conda list

    # Install Jupyter
    - name: Setup Jupyter
      shell: bash -l {0}
      run: |
      #  conda list
        # conda create -n bmlip python=3.7 anaconda
        conda install -c anaconda jupyter
      #  conda activate bmlip
      #  conda install -c anaconda jupyter
      #  conda install -c conda-forge notebook
      #  conda install -c conda-forge jupyterlab
      #  conda list

    # Install Julia
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.1.0
      with:
        version: 1.3
        arch: x64
        show-versioninfo: true

    # Add IJulia kernel to Jupyter
    - name: Setup IJulia
      run: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.status(); using IJulia; installkernel("julia")'

    # Run lesson notebooks
    - name: Test notebook 00
      run: |
        cd BMLIP/lessons/notebooks
        jupyter nbconvert --to notebook --inplace --execute 00-Course-Outline-and-Admin-Issues.ipynb
